### ISSUE TITLE
数据准备

### ISSUE THREAD

**Issue by smileSQSQ** [TobiasLee/MTA-LSTM-TensorFlow#11]
你好，我正在读这篇论文，看到了你的实现，您可以分享一下你数据处理部分的代码吗？因为我是新手，代码还看不太明白，所以不清楚数据是如何处理的，您能分享一下吗，谢谢。

**Comment by TobiasLee** [comment]
主要对文本进行了词表构建、Tokenize 化，具体的代码可以看下面这篇文章
https://zhuanlan.zhihu.com/p/31767633
