### ISSUE TITLE
Some question about the evaluation part.

### ISSUE THREAD

**Issue by caoxu915683474** [TobiasLee/MTA-LSTM-TensorFlow#4]
Hi ! TobiasLee. 
Thanks for sharing this good work! I got some problem with the evaluation part. I read your evaluation.py and found that you didn't restore the model. Maybe I am not right, can you help me?
Thank you!

**Comment by TobiasLee** [comment]
Yes. It seems that I deleted the code of restoring the model. I will add it to the evaluation.py. Thanks for the notification~
