### ISSUE TITLE
关于生成的UNk

### ISSUE THREAD

**Issue by nlpofwhat** [TobiasLee/MTA-LSTM-TensorFlow#8]
请问一下你生成的文本为什么没有UNK,我生成的文本又一堆的UNK,END,PAD字符

**Comment by TobiasLee** [comment]
README 中的例子是去掉特殊符号的

**Comment by nlpofwhat** [comment]
那你的效果达到了论文的效果吗，感觉原论文给出的测试太少了，我做的实验发现很多句子只是语法还可以，但是语义上不通顺，指代不明一而且一堆的UNK,END,PAD。可能与原文唯一的区别就是他用了大量的预料进行词向量的预训练，但是我不认为这个对模型有很大的改善
 



------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 晚上6:40
收件人: "TobiasLee/MTA-LSTM-TensorFlow"<MTA-LSTM-TensorFlow@noreply.github.com>; 
抄送: "@My heart will go on."<952167295@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TobiasLee/MTA-LSTM-TensorFlow] 关于生成的UNk (#8)




README 中的例子是去掉特殊符号的

**Comment by TobiasLee** [comment]
我没有做评测，肉眼观察还是质量可以的；pre-train word embedding 对于生成的效果还是有提升的

**Comment by nlpofwhat** [comment]
请问您最后的损失函数降到多少了，我的损失函数从400多到200后面就很难降下去了

**Comment by nbdwddbf** [comment]
请问您Data文件夹里面的数据有嘛，我是一个新手，求分享。

**Comment by nlpofwhat** [comment]
原论文有下载连接的

**Comment by nbdwddbf** [comment]
> 原论文有下载连接的

论文里面的下载链接就是“https://github.com/hit-computer/MTA-LSTM“  这个仓库啊，没有那个vec.text,求分享vec.text,以及文章的TrainingData用的是那个composition.txt还是zhihu.txt啊，求教！！！

**Comment by nlpofwhat** [comment]
下面有数据的下载链接，vec.txt是可以自己训练的词向量
 



------------------ 原始邮件 ------------------
发件人: "nbdwddbf"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:06
收件人: "TobiasLee/MTA-LSTM-TensorFlow"<MTA-LSTM-TensorFlow@noreply.github.com>; 
抄送: "@My heart will go on."<952167295@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TobiasLee/MTA-LSTM-TensorFlow] 关于生成的UNk (#8)



 
原论文有下载连接的
  
论文里面的下载链接就是“https://github.com/hit-computer/MTA-LSTM“这个仓库啊，没有那个vec.text,求分享vec.text,以及文章的TrainingData用的是那个composition.txt还是zhihu.txt啊，求教！！！

**Comment by nbdwddbf** [comment]
请问您这个项目中，vec是通过哪个txt来训练的啊

**Comment by nbdwddbf** [comment]
可以分享一下您的data这一部分数据呢?谢谢啦

**Comment by nbdwddbf** [comment]
如您能分享，非常的感谢！！！（附邮箱：2927572356@qq.com）

**Comment by nlpofwhat** [comment]
这是下载链接，我用的是这个https://pan.baidu.com/s/1_JPh5-g2rry2QmbjQ3pZ6w
 



------------------ 原始邮件 ------------------
发件人: "nbdwddbf"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:14
收件人: "TobiasLee/MTA-LSTM-TensorFlow"<MTA-LSTM-TensorFlow@noreply.github.com>; 
抄送: "@My heart will go on."<952167295@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TobiasLee/MTA-LSTM-TensorFlow] 关于生成的UNk (#8)




可以分享一下您的data这一部分数据呢?谢谢啦

**Comment by nbdwddbf** [comment]
可以加您qq嘛？我有不懂的想咨询您

**Comment by nlpofwhat** [comment]
欢迎讨论
 



------------------ 原始邮件 ------------------
发件人: "nbdwddbf"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 下午2:39
收件人: "TobiasLee/MTA-LSTM-TensorFlow"<MTA-LSTM-TensorFlow@noreply.github.com>; 
抄送: "@My heart will go on."<952167295@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TobiasLee/MTA-LSTM-TensorFlow] 关于生成的UNk (#8)




可以加您qq嘛？我有不懂的想咨询您

**Comment by nbdwddbf** [comment]
已加，求通过
