### ISSUE TITLE
composition数据集上测试

### ISSUE THREAD

**Issue by nlpofwhat** [TobiasLee/MTA-LSTM-TensorFlow#9]
为什么我用composition数据集训练效果非常差啊，没有一个句子能看的

**Comment by TobiasLee** [comment]
可以对比一下代码 以及论文中的细节 看看有没有不同的地方 我展示的例子就是训练的结果

**Comment by nlpofwhat** [comment]
我只是发现你的代码和原来那个在实现attention的时候少了个偏置其他的没发现什么问题🤣------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>
发送时间: 2019年11月11日(星期一) 中午11:33
收件人: "TobiasLee/MTA-LSTM-TensorFlow"<MTA-LSTM-TensorFlow@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TobiasLee/MTA-LSTM-TensorFlow] composition数据集上测试 (#9)



可以对比一下代码 以及论文中的细节 看看有没有不同的地方 我展示的例子就是训练的结果
 
&mdash;

**Comment by nlpofwhat** [comment]
大佬可以加个好友吗？想请教您一些问题





------------------ 原始邮件 ------------------
发件人: Tobias Lee <notifications@github.com&gt;
发送时间: 2019年11月20日 08:50
收件人: TobiasLee/MTA-LSTM-TensorFlow <MTA-LSTM-TensorFlow@noreply.github.com&gt;
抄送: learnby <952167295@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[TobiasLee/MTA-LSTM-TensorFlow] composition数据集上测试 (#9)




Closed #9.
